### ISSUE TITLE
problems of some pages on iCub web

### ISSUE THREAD

**Issue by matejhof** [robotology/robotology-documentation#3]
Hi, don't know where to report this, but some pages appear to be broken: 

- [https://www.iit.it/web/icub/resources](https://www.iit.it/web/icub/resources)
- [https://icub.iit.it/web/icub/about-us/icub-history](https://icub.iit.it/web/icub/about-us/icub-history)

**Comment by pattacini** [comment]
Thanks for reporting @matejhof!

The first link doesn't seem a valid URL as the actual page is instead https://icub.iit.it/community/resources.

Our IT staff just fixed the second point ✅

**Comment by matejhof** [comment]
Ok! 
I got the wrong `community` link from elsewhere - maybe from the history page. Looking at [https://icub.iit.it/web/icub/about-us/icub-history](https://icub.iit.it/web/icub/about-us/icub-history), all or most of the links from there seem to be wrong, containing `web` in the URL:

- [https://www.iit.it/web/icub/resources](https://www.iit.it/web/icub/resources)
- [https://icub.iit.it/web/icub/icub-robot](https://icub.iit.it/web/icub/icub-robot)
- [https://icub.iit.it/web/icub/products/yarp](https://icub.iit.it/web/icub/products/yarp)
- [https://icub.iit.it/web/icub/r1-robot](https://icub.iit.it/web/icub/r1-robot)

**Comment by pattacini** [comment]
Thanks @matejhof 
I'll report also these points.

**Comment by pattacini** [comment]
They should be solved.
